# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CodeProjects\DiscordServerManager\src\resources\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(370, 80, 83, 29))
        self.login.setObjectName("login")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(180, 110, 571, 61))
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.errorLabel.setObjectName("errorLabel")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(260, 10, 341, 64))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.discordTokenLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.discordTokenLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.discordTokenLineEdit.setObjectName("discordTokenLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.discordTokenLineEdit)
        self.discordTokenLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.discordTokenLabel.setObjectName("discordTokenLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.discordTokenLabel)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 170, 781, 381))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 60, 761, 191))
        self.label.setStyleSheet("QLabel { font-size: 15px; }")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.how_to = QtWidgets.QLabel(self.groupBox)
        self.how_to.setGeometry(QtCore.QRect(250, 30, 291, 31))
        self.how_to.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"}")
        self.how_to.setScaledContents(False)
        self.how_to.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.how_to.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.how_to.setObjectName("how_to")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 290, 681, 71))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login.setText(_translate("MainWindow", "Login"))
        self.discordTokenLabel.setText(_translate("MainWindow", "Discord Token"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "Disclamer: This program is against Discord\'s Terms Of Service. Your account can get banned for using this program. \n"
"                WE ARE NOT RESPONSIBLE FOR ANY ACTIONS YOU MADE.\n"
"\n"
"1: Open https://discord.com with your account logged in.\n"
"2: Open Devtools by pressing CTRL + SHIFT + I\n"
"3: Once the developer tools are open, you can click on the \"Console\" tab.\n"
"4: Copy the code below and paste it on the \"Console\" Tab.\n"
"5: Copy the token printed on the \"Console\" Tab. It should appear after pasting the code.\n"
"6: Paste the token to the field above that says \"Discord Token\""))
        self.how_to.setText(_translate("MainWindow", "How to get Discord Token?"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "(webpackChunkdiscord_app.push([[\'\'],{},e=>{m=[];for(let c in e.c)m.push(e.c[c])}]),m).find(m=>m?.exports?.default?.getToken!==void 0).exports.default.getToken()"))
